oidolee/dreams_proejct

index.html

title edit 33

---

resource/page_3/test.html

page_3 title edti

---

resource/page_2/test.html

page_2 타이틀 수정

---

resource/css/common/page4_board.css
resource/page_4/dreamsBoard.html
resource/page_4/news.html
resource/page_4/qna.html
resource/page_4/qnaSky.html
resource/page_4/qnaTiket.html

page_4 업데이트

---

resource/page_6/Introduce.html
resource/page_6/amenity.html
resource/page_6/goodsExchange.html
resource/page_6/goodsRefund.html
resource/page_6/location.html
resource/page_6/parking.html
resource/page_6/seatChange.html
resource/page_6/seatRefund.html
resource/page_6/stadium.html
resource/page_6/templet.html

page_6 24-01-04 작업

---

resource/page_2/DreamsMembership.html
resource/page_2/childrenMembership.html
resource/page_2/groupViewing.html
resource/page_2/membership.html
resource/page_2/productAdd.html
resource/page_2/productAddList.html
resource/page_2/reservationInfo.html
resource/page_2/ticketFee.html

단체관람 멤버쉽 듬린이멤버쉽 작성
css 글자 색 바꿔야 함.. 이미지 불러와야함
단체관람 멤버쉽 듬린이멤버쉽 페이지 연결 해놨음

page_2 단체관람 멤버쉽 듬린이멤버쉽 작성

---

resource/page_6/amenity.html
resource/page_6/location.html
resource/page_6/parking.html

Introduce, stadium, amenity, location, parking  => css 작업중..

page_6 24-01-04 작업2

---

resource/page_6/Introduce.html
resource/page_6/amenity.html
resource/page_6/location.html
resource/page_6/parking.html
resource/page_6/stadium.html

거의 완성
introduce
stadium
location
parking

page_6 24-01-05 작업

---

resource/css/common/page2_ticket.css
resource/page_2/dayticket.html
resource/page_2/purchase.html

결제창 구현
아직 표 갯수 마이너스표시와 
할인율 마이너스 표시 아직 구현 안됐음

page_2 결제창

---

resource/css/admin/basket.css
resource/css/customer/join.css
resource/page_1/basket.html
resource/page_1/join.html
resource/page_1/join_edit.html
resource/page_1/login.html
resource/page_1/test.html

page_1 장바구니완료

---

resource/page_6/goodsExchange.html
resource/page_6/goodsRefund.html
resource/page_6/myPage.html

amenity, goodsExchange, goodsRefund, seatRefund 수정 
seatChange 애매해서 삭제하고 myPage 새로 추가

page_6 업데이트

---

resource/page_2/purchase.html
resource/page_2/ticketFee.html

티켓 예매 버튼에 결제창 연결 및 창 열림시 창 크기 수정

Page 2 업데이트

---

resource/page_6/Introduce.html
resource/page_6/amenity.html
resource/page_6/goodsExchange.html
resource/page_6/goodsRefund.html
resource/page_6/location.html
resource/page_6/myPage.html
resource/page_6/parking.html
resource/page_6/seatRefund.html
resource/page_6/stadium.html

각종 디테일 수정
amenity 만들어놓은 파일이 없어져서 집에서 확인하고 다시 올리겠습니다.

page_6 2024/01/08

---

resource/css/common/page2_ticket.css
resource/page_2/DreamsMembership.html
resource/page_2/childrenMembership.html
resource/page_2/discountTicket.html
resource/page_2/groupViewing.html
resource/page_2/purchaseGoods.html
resource/page_2/purchaseTicket.html
resource/page_2/reservationInfo.html
resource/page_2/templet.html
resource/page_2/ticketFee.html

티켓 구매창 구현 및 상품구매창 구현중

---

resource/page_1/basket.html
resource/page_1/join.html
resource/page_1/joinAction.html
resource/page_1/join_edit.html

page_1 디테일수정

---

resource/page_6/Introduce.html
resource/page_6/amenity.html
resource/page_6/goodsRefund.html
resource/page_6/location.html
resource/page_6/myPage.html
resource/page_6/parking.html
resource/page_6/seatRefund.html
resource/page_6/stadium.html
resource/page_6/templet.html

remove double slash

---

resource/page_4/test222222.html

page_4 테스트

---

resource/page_6/Introduce.html
resource/page_6/amenity.html
resource/page_6/goodsRefund.html
resource/page_6/location.html
resource/page_6/myPage.html
resource/page_6/parking.html
resource/page_6/seatRefund.html
resource/page_6/stadium.html

링크 연결 [GAMES, STATS, BOARDS(다운로드, 응원단) 빼고 다함]
width 1280px
margin 0 auto 적용

2024-01-10 수정

---

resource/page_2/DreamsMembership.html
resource/page_2/childrenMembership.html
resource/page_2/discountTicket.html
resource/page_2/groupViewing.html
resource/page_2/purchaseTicket.html
resource/page_2/reservationInfo.html
resource/page_2/ticketFee.html

결제창 수정 및 페이지 링크 수정

---

index.html

24-01-11 git push

---

resource/page_6/Introduce.html
resource/page_6/amenity.html
resource/page_6/goodsRefund.html
resource/page_6/location.html
resource/page_6/myPage.html
resource/page_6/parking.html
resource/page_6/seatRefund.html
resource/page_6/stadium.html
resource/page_6/test.html

page_6 링크정리

---

resource/admin/ticket/ticket copy.html
resource/page_2/DreamsMembership.html
resource/page_2/childrenMembership.html
resource/page_2/discountTicket.html
resource/page_2/groupViewing.html
resource/page_2/reservationInfo.html
resource/page_2/skybox.html
resource/page_2/ticketFee.html

관리자 티켓페이지 수정 및 페이지 링크수정

---

resource/admin/ticket/ticket copy.html
resource/admin/ticket/ticket detail.html

관리자 티켓페이지 수정

---

resource/page_4/coaching.html
resource/page_4/dreamsBoarDetail.html
resource/page_4/dreamsBoard.html
resource/page_4/dreamsBoardWrite.html
resource/page_4/news.html
resource/page_4/players.html
resource/page_4/qna.html
resource/page_4/qnaEtc.html
resource/page_4/qnaMd.html
resource/page_4/qnaParking.html
resource/page_4/qnaSky.html
resource/page_4/qnaTiket.html
resource/page_4/stats.html
resource/page_4/steff.html
resource/page_4/test.html

Page 4 링크정리 재업

---

resource/page_1/login_id.html

page_1 아이디찾기페이지  추가

---

resource/page_1/basket.html
resource/page_1/join.html
resource/page_1/joinAction.html
resource/page_1/join_edit.html
resource/page_1/login.html
resource/page_1/login_id.html

page_1 아이디찾기 디벨롭
